In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv("data4.csv")
d4=data.to_numpy()

In [3]:
data

1  1.1  1.2  1.3  1.4  1.5  0  1.6  1.7
0   1    1    1    1    1    1  0    0    1
1   1    1    1    1    1    1  1    1    0
2   1    1    1    1    1    0  0    1    1
3   1    1    1    1    1    0  0    0    1
4   1    1    1    0    1    1  0    1    1
5   1    1    0    1    1    1  0    1    0
6   1    1    1    0    1    1  0    0    1
7   1    1    1    0    1    0  0    1    1
8   1    1    1    0    1    0  0    0    1
9   0    1    1    1    1    1  0    1    1
10  0    1    1    1    1    1  0    0    1
11  1    0    1    1    1    1  0    1    0
12  0    1    1    1    1    0  0    1    1
13  1    1    0    1    0    1  0    1    0
14  1    0    0    1    1    1  0    1    0
15  1    0    0    1    0    1  1    1    0
16  0    1    1    1    1    0  0    0    1
17  1    0    1    1    1    1  1    1    0
18  0    1    1    0    1    1  0    1    1

In [4]:
d4

array([[1, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 1]], dtype=int64)

In [5]:
k=5

In [6]:
test=pd.read_csv("test4.csv")
t4=test.to_numpy()

In [7]:
t4

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0]], dtype=int64)

In [8]:
euclid=np.zeros((d4.shape[0],t4.shape[0]))
euclid

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
for i in range(0,t4.shape[0]):
    for j in range(0,d4.shape[0]):
        euclid[j,i]=np.sum(np.square(d4[j,0:8]-t4[i,:]))
euclid    

array([[5., 3., 2.],
       [7., 5., 4.],
       [5., 3., 2.],
       [4., 2., 1.],
       [5., 3., 4.],
       [5., 5., 4.],
       [4., 2., 3.],
       [4., 2., 3.],
       [3., 1., 2.],
       [7., 3., 2.],
       [6., 2., 1.],
       [5., 5., 4.],
       [6., 2., 1.],
       [4., 6., 5.],
       [4., 6., 5.],
       [4., 8., 7.],
       [5., 1., 0.],
       [6., 6., 5.],
       [6., 2., 3.]])

In [11]:
array_sort=np.argsort(euclid,axis=0)
array_sort

array([[ 8, 16, 16],
       [ 3,  8, 12],
       [ 6, 18,  3],
       [ 7, 12, 10],
       [15,  3,  0],
       [14, 10,  8],
       [13,  6,  9],
       [ 0,  7,  2],
       [16,  0,  7],
       [ 2,  4,  6],
       [ 4,  2, 18],
       [ 5,  9,  5],
       [11, 11,  4],
       [18,  1, 11],
       [10,  5,  1],
       [17, 17, 17],
       [12, 13, 13],
       [ 1, 14, 14],
       [ 9, 15, 15]], dtype=int64)

In [14]:
k=5
knn=np.zeros((k,t4.shape[0]))
for i  in range(0,t4.shape[0]):
    for j in range(0,k):
        knn[j,i]=d4[array_sort[j,i],8]
knn        

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.]])

In [15]:
result=[]
for i in range(0,knn.shape[1]):
    b=knn[:,i]
    b=b.astype(int)
    counts=np.bincount(b)
    maxlabel=np.argmax(counts)
    result=np.append(result,maxlabel)
result    

array([1., 1., 1.])