In [1]:
#LAB CYCLE 3

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
dataset=pd.read_csv("data3.csv")
dataset

D  X1  X2  X3  X4  X5  X6
0    0   3   3   3   4   2   4
1    0   3   2   3   5   4   3
2    1   5   3   3   3   3   5
3    0   5   4   3   3   3   5
4    0   5   4   3   3   3   5
..  ..  ..  ..  ..  ..  ..  ..
124  1   5   2   4   4   2   3
125  0   5   3   3   4   4   5
126  0   5   3   3   4   4   4
127  0   3   2   3   3   5   4
128  0   4   1   3   3   3   4

[129 rows x 7 columns]

In [6]:
total=dataset.shape[0]
total

129

In [7]:
fzero=dataset['D'][dataset['D']==0].count()
fzero

59

In [8]:
fone=dataset['D'][dataset['D']==1].count()
fone

70

In [9]:
pzero=fzero/total
pzero

0.4573643410852713

In [10]:
pone=fone/total
pone

0.5426356589147286

In [26]:
dzero=np.zeros((5,6))
done=np.zeros((5,6))

In [27]:
for i in range(0,6):
    for j in range(0,5):
         dzero[j][i]=dataset['X'+str(i+1)][dataset['D']==0][dataset['X'+str(i+1)]==j+1].count()

In [28]:
dzero

array([[ 1., 15.,  4.,  0.,  5.,  1.],
       [ 0., 14.,  7.,  5.,  9.,  1.],
       [16., 18., 34., 24., 15., 16.],
       [25., 10.,  9., 21., 22., 24.],
       [17.,  2.,  5.,  9.,  8., 17.]])

In [29]:
for i in range(0,6):
    for j in range(0,5):
        done[j][i]=dataset['X'+str(i+1)][dataset['D']==1][dataset['X'+str(i+1)]==j+1].count()

In [30]:
done

array([[ 0., 13.,  2.,  1.,  1.,  0.],
       [ 0., 23.,  9.,  1.,  8.,  0.],
       [ 7., 22., 25., 24., 11.,  5.],
       [18.,  8., 24., 30., 30., 28.],
       [45.,  4., 10., 14., 20., 37.]])

In [31]:
zeroprobzero=np.zeros((6))
oneprobzero=np.zeros((6))

In [32]:
for i in range(0,5):
    for j in range(0,6):
        if(dzero[i][j]==0):
            zeroprobzero[j]=zeroprobzero[j]+1
           
            
            

In [33]:
zeroprobzero 

array([1., 0., 0., 1., 0., 0.])

In [34]:
for i in range(0,5):
    for j in range(0,6):
        if(done[i][j]==0):
            oneprobzero[j]=oneprobzero[j]+1
oneprobzero

array([2., 0., 0., 0., 0., 2.])

In [36]:
dzeroprob=np.zeros((5,6))
doneprob=np.zeros((5,6))
done

array([[ 0., 13.,  2.,  1.,  1.,  0.],
       [ 0., 23.,  9.,  1.,  8.,  0.],
       [ 7., 22., 25., 24., 11.,  5.],
       [18.,  8., 24., 30., 30., 28.],
       [45.,  4., 10., 14., 20., 37.]])

In [37]:
for n in range(0,6):
    if(zeroprobzero[n]>0):
        for j in range(0,5):
            dzeroprob[j][n]=(dzero[j][n]+1)/(fzero+5)
    else:
        for j in range(0,5):
            dzeroprob[j][n]=dzero[j][n]/fzero
dzeroprob

array([[0.03125   , 0.25423729, 0.06779661, 0.015625  , 0.08474576,
        0.01694915],
       [0.015625  , 0.23728814, 0.11864407, 0.09375   , 0.15254237,
        0.01694915],
       [0.265625  , 0.30508475, 0.57627119, 0.390625  , 0.25423729,
        0.27118644],
       [0.40625   , 0.16949153, 0.15254237, 0.34375   , 0.37288136,
        0.40677966],
       [0.28125   , 0.03389831, 0.08474576, 0.15625   , 0.13559322,
        0.28813559]])

In [38]:
for n in range(0,6):
    if(oneprobzero[n]>0):
        for j in range(0,5):
            doneprob[j][n]=(done[j][n]+1)/(fone+5)
    else:
        for j in range(0,5):
            doneprob[j][n]=done[j][n]/fone
doneprob

array([[0.01333333, 0.18571429, 0.02857143, 0.01428571, 0.01428571,
        0.01333333],
       [0.01333333, 0.32857143, 0.12857143, 0.01428571, 0.11428571,
        0.01333333],
       [0.10666667, 0.31428571, 0.35714286, 0.34285714, 0.15714286,
        0.08      ],
       [0.25333333, 0.11428571, 0.34285714, 0.42857143, 0.42857143,
        0.38666667],
       [0.61333333, 0.05714286, 0.14285714, 0.2       , 0.28571429,
        0.50666667]])

In [39]:
testset=pd.read_csv("test3.csv")
testset

D  X1  X2  X3  X4  X5  X6
0   0   5   1   4   4   4   5
1   0   5   2   2   4   4   5
2   0   5   3   5   4   5   5
3   1   3   4   4   5   1   3
4   1   5   1   5   5   5   5
5   1   4   3   3   4   4   4
6   1   5   5   1   1   5   1
7   0   4   4   4   4   1   3
8   1   5   2   3   4   4   3
9   0   5   3   3   1   3   5
10  1   5   2   3   4   2   5
11  1   5   3   3   4   4   5
12  0   4   3   3   4   4   5
13  0   5   3   2   5   5   5

In [40]:
ttotal=testset.shape[0]
ttotal

14

In [41]:
#confusion matrix


In [42]:
tp=0
tn=0
fp=0
fn=0
for n in range(0,ttotal):
    a=1
    b=1
    for i in range(1,6):
        k=testset.at[n,'X'+str(i)]
        a=a*dzeroprob[k-1][i-1]
        b=b*doneprob[k-1][i-1]
        if i==5:
            break
    a=a*pzero
    b=b*pone
    if(a>b):
        predict=0
    else:
        predict=1
    d=testset.at[n,'D']
    if(d==1 and predict==1):
        tp=tp+1
    elif(d==1 and predict==0):
        tn=tn+1
    elif(d==0 and predict==1):
        fp=fp+1
    else:
        fn=fn+1

In [43]:
confusion=np.array([[tp,fp],[fn,tn]])
confusion

array([[5, 4],
       [3, 2]])

In [44]:
correctness=(tp+tn)/(tp+tn+fp+fn)
print("correctness = ",correctness)

correctness =  0.5


In [45]:
erorrness=(fp+fn)/(tp+tn+fp+fn)
print("erorrness = ",erorrness)

erorrness =  0.5


In [46]:
precision=tp/(tp+fp)
print("precision = ",precision)

precision =  0.5555555555555556


In [47]:
recall=tp/(tp+fn)
print("recall = ",recall)

recall =  0.625
